# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#image: node:6.9.0

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
   - npm run dist

lint:
  stage: lint
  script:
   - npm run lint

test:
  stage: test
  script:
   - npm run test
#  only:
#   - master
#   - develop
