language: node_js

node_js:
  - "6"
  - "8"

before_install:
  - npm i -g npm
  - npm install -g eslint

install:

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - npm run build
