language: node_js
node_js:
  - "4"
  - "5"
before_install:
  - npm i -g npm@5.0.3
install:
  - npm install -g eslint
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run build
